"""Name required

Revision ID: 0264a5a526f9
Revises: 04d408291b87
Create Date: 2024-08-19 11:13:31.136030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0264a5a526f9'
down_revision = '04d408291b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('namereq', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_column('namereq')

    # ### end Alembic commands ###
