"""empty message

Revision ID: 2d5d7964ae6e
Revises: 189f53fc9f72
Create Date: 2024-07-23 13:27:20.457698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5d7964ae6e'
down_revision = '189f53fc9f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=36), nullable=False))
        batch_op.drop_constraint('payments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payments_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
