"""Added count to presets

Revision ID: 540f3ec3bcf9
Revises: 52fe0943bb8c
Create Date: 2024-07-15 18:52:07.445189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540f3ec3bcf9'
down_revision = '52fe0943bb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
