"""empty message

Revision ID: 56ad32521f2e
Revises: 65aabeb1d2c7
Create Date: 2024-08-03 01:31:09.777531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ad32521f2e'
down_revision = '65aabeb1d2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_cost', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('credit_cost')

    # ### end Alembic commands ###
