"""empty message

Revision ID: 747ac603f3ed
Revises: 327e991acc68
Create Date: 2024-07-17 23:35:01.261867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747ac603f3ed'
down_revision = '327e991acc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=240),
               existing_nullable=False)

    # ### end Alembic commands ###
