"""Changed role length

Revision ID: 7f954d03590e
Revises: 7a19104646dd
Create Date: 2024-07-02 10:28:51.849606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f954d03590e'
down_revision = '7a19104646dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=240),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)

    # ### end Alembic commands ###
