"""empty message

Revision ID: 8756cd2950c0
Revises: 2d5d7964ae6e
Create Date: 2024-07-23 13:52:44.153074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8756cd2950c0'
down_revision = '2d5d7964ae6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('payments_user_email_fkey', type_='foreignkey')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('payments_user_email_fkey', 'users', ['user_email'], ['id'])

    # ### end Alembic commands ###
