"""Arrays of balance and credits 3

Revision ID: b5d86241ec7d
Revises: 6bb2307576f7
Create Date: 2024-06-28 18:44:05.023231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d86241ec7d'
down_revision = '6bb2307576f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               nullable=False)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               nullable=True)

    # ### end Alembic commands ###
