"""empty message

Revision ID: db86d60cf84b
Revises: 56ad32521f2e
Create Date: 2024-08-03 11:35:18.813591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db86d60cf84b'
down_revision = '56ad32521f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('credit_cost',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('credit_cost',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
