"""empty message

Revision ID: 01ff93270c49
Revises: 540f3ec3bcf9
Create Date: 2024-07-15 22:24:31.904370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ff93270c49'
down_revision = '540f3ec3bcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
