"""empty message

Revision ID: 04d408291b87
Revises: 9668baa1daa7
Create Date: 2024-08-11 00:55:16.654183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d408291b87'
down_revision = '9668baa1daa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('credit_cost',
               existing_type=sa.NUMERIC(precision=38, scale=20),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('credit_cost',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=38, scale=20),
               existing_nullable=True)

    # ### end Alembic commands ###
