"""empty message

Revision ID: 327e991acc68
Revises: 01ff93270c49
Create Date: 2024-07-15 23:47:28.042334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327e991acc68'
down_revision = '01ff93270c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excerpt', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_column('excerpt')

    # ### end Alembic commands ###
