"""Preset table

Revision ID: 3e9fac62ba81
Revises: 7f954d03590e
Create Date: 2024-07-13 10:19:02.519031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9fac62ba81'
down_revision = '7f954d03590e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('imagelink', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('isNsfw', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_column('isNsfw')
        batch_op.drop_column('imagelink')
        batch_op.drop_column('role')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
