"""Arrays of balance and credits 2

Revision ID: 6bb2307576f7
Revises: f29d3c952edb
Create Date: 2024-06-28 18:40:41.540459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb2307576f7'
down_revision = 'f29d3c952edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               nullable=True)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               nullable=False)

    # ### end Alembic commands ###
