"""Updated balance and credits columns to arrays

Revision ID: 7a19104646dd
Revises: 84181bf0f823
Create Date: 2024-06-28 19:20:26.959664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a19104646dd'
down_revision = '84181bf0f823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(precision=38, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
