"""Updated balance and credits columns to arrays

Revision ID: 84181bf0f823
Revises: 8c88dfa229c1
Create Date: 2024-06-28 19:06:29.074428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84181bf0f823'
down_revision = '8c88dfa229c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               nullable=False)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               nullable=True)

    # ### end Alembic commands ###
