"""Updated balance and credits columns to arrays

Revision ID: 8c88dfa229c1
Revises: b5d86241ec7d
Create Date: 2024-06-28 18:57:36.275701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c88dfa229c1'
down_revision = 'b5d86241ec7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               nullable=True)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               nullable=False)

    # ### end Alembic commands ###
