"""empty message

Revision ID: 9668baa1daa7
Revises: e98907970f4d
Create Date: 2024-08-11 00:53:26.094854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9668baa1daa7'
down_revision = 'e98907970f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('credit_cost',
               existing_type=sa.NUMERIC(precision=2, scale=20),
               type_=sa.Numeric(precision=38, scale=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('credit_cost',
               existing_type=sa.Numeric(precision=38, scale=20),
               type_=sa.NUMERIC(precision=2, scale=20),
               existing_nullable=True)

    # ### end Alembic commands ###
