"""empty message

Revision ID: e98907970f4d
Revises: db86d60cf84b
Create Date: 2024-08-11 00:48:26.641498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98907970f4d'
down_revision = 'db86d60cf84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('credit_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=2, scale=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('credit_cost',
               existing_type=sa.Numeric(precision=2, scale=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
