"""add created_at column to presets

Revision ID: f73fc78967b8
Revises: 3e9fac62ba81
Create Date: 2024-07-14 19:54:32.560255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73fc78967b8'
down_revision = '3e9fac62ba81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
